on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3
      - uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: test read
        run: |
          node index.js